# Retrieval Evaluation using Haystack

## Statistical Evaluation
pada bagian pertama ini kita akan melakukan statistical evaluation pada result hasil Retrieval

### Pipeline Definition
pertama-tama dilakukan definisi pipeline, disini kita akan buat pipeline retrieval untuk mengambil data dari mongodb atlas

In [1]:
from haystack import Pipeline
from haystack.components.embedders import SentenceTransformersTextEmbedder
from haystack_integrations.components.retrievers.mongodb_atlas import MongoDBAtlasEmbeddingRetriever
from haystack_integrations.document_stores.mongodb_atlas import MongoDBAtlasDocumentStore

C:\Users\GULO\.conda\envs\dibimbing\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
%env MONGO_CONNECTION_STRING=mongodb+srv://user_dibimbing:gasterus@cluster0.zse9okn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

env: MONGO_CONNECTION_STRING=mongodb+srv://user_dibimbing:gasterus@cluster0.zse9okn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0


In [3]:
document_store = MongoDBAtlasDocumentStore(
    database_name="dibimbing",
    collection_name="context_qa",
    vector_search_index="vector_index_qa",
)

In [4]:
pipeline = Pipeline()
pipeline.add_component("embedder",SentenceTransformersTextEmbedder())
pipeline.add_component("retriever",MongoDBAtlasEmbeddingRetriever(document_store=document_store,top_k=10))
pipeline.connect("embedder","retriever")

🚅 Components
  - embedder: SentenceTransformersTextEmbedder
  - retriever: MongoDBAtlasEmbeddingRetriever
🛤️ Connections
  - embedder.embedding -> retriever.query_embedding (List[float])

### Load Dataset
Selanjutnya dilakukan load dataset untuk evaluasi. Disini kita akan menggunakan Stanford Question Answering Dataset (SQuAD). SQuAD adalah sebuah dataset yang tersusun dari pertanyaan, context, dan jawban yang dibuat dengan menggunakan data pengetahuan dari Wikipedia.  
Source: https://rajpurkar.github.io/SQuAD-explorer/

In [5]:
import json
with open("datasets/qa.json","r") as f:
    dataset = json.load(f)

In [6]:
from haystack import Document
questions = []
answers = []
contexts = []
for data in dataset['data']:
  for p in data['paragraphs']:
    doc = Document(content=p['context'])
    contexts.append(doc)
    for qa in p["qas"]:
      questions.append(qa['question'])
      answers.append(qa['answers'][0]['text'])
      break

In [7]:
selected_questions = questions[200:210]
selected_answers = answers[200:210]
selected_contexts = contexts[200:210]

In [8]:
selected_contexts[0]

Document(id=5ff992ba2814bb19cd68848b190eebd717b80bd27243c7d44dca3ab6d65a5a5e, content: 'French Huguenots made two attempts to establish a haven in North America. In 1562, naval officer Jea...')

### Retrieve Data

In [9]:
def get_result(questions):
    results = []
    for q in questions:
        result = pipeline.run({"embedder":{"text":q}})
        results.append(result["retriever"]["documents"])
    return results

In [10]:
results = get_result(selected_questions)

C:\Users\GULO\.conda\envs\dibimbing\Lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Batches: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.25it/s]


## Recall Evaluations

In [11]:
from haystack.components.evaluators import DocumentRecallEvaluator

In [12]:
recall_evaluator = DocumentRecallEvaluator()

In [13]:
recall_result = recall_evaluator.run(
    ground_truth_documents=[[s] for s in selected_contexts],
    retrieved_documents=results
)

In [14]:
print(f"Score: {recall_result['score']}")

Score: 1.0


In [19]:
import numpy as np
individual_scores = np.array(recall_result["individual_scores"])

In [20]:
print(individual_scores)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [22]:
np.argwhere(individual_scores==1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]], dtype=int64)

In [23]:
results_data_check = [d.content for d in results[9]]

In [24]:
results_data_check

["In what became known as the St. Bartholomew's Day Massacre of 24 August – 3 October 1572, Catholics killed thousands of Huguenots in Paris. Similar massacres took place in other towns in the weeks following. The main provincial towns and cities experiencing the Massacre were Aix, Bordeaux, Bourges, Lyons, Meaux, Orleans, Rouen, Toulouse, and Troyes. Nearly 3,000 Protestants were slaughtered in Toulouse alone. The exact number of fatalities throughout the country is not known. On 23–24 August, between about 2,000 and 3,000 Protestants were killed in Paris and between 3,000 and 7,000 more in the French provinces. By 17 September, almost 25,000 Protestants had been massacred in Paris alone. Beyond Paris, the killings continued until 3 October. An amnesty granted in 1573 pardoned the perpetrators.[citation needed]",
 "The Catholic Church in France and many of its members opposed the Huguenots. Some Huguenot preachers and congregants were attacked as they attempted to meet for worship. Th

### MRR Evaluations

In [25]:
from haystack.components.evaluators import DocumentMRREvaluator
MRR_evaluator = DocumentMRREvaluator()
MRR_result = MRR_evaluator.run(
    ground_truth_documents=[[s] for s in selected_contexts],
    retrieved_documents=results
)

In [26]:
print(f"MRR Score: {MRR_result['score']}")

MRR Score: 0.7583333333333333


In [27]:
MRR_individual_scores = np.array(MRR_result["individual_scores"])

In [28]:
MRR_individual_scores

array([0.5       , 1.        , 0.5       , 0.25      , 1.        ,
       1.        , 0.33333333, 1.        , 1.        , 1.        ])

In [29]:
np.argwhere(MRR_individual_scores==0.5)

array([[0],
       [2]], dtype=int64)

In [30]:
results_data_check = [d.content for d in results[0]]
results_data_check

['In the early years, many Huguenots also settled in the area of present-day Charleston, South Carolina. In 1685, Rev. Elie Prioleau from the town of Pons in France, was among the first to settle there. He became pastor of the first Huguenot church in North America in that city. After the Revocation of the Edict of Nantes in 1685, several Huguenot families of Norman and Carolingian nobility and descent, including Edmund Bohun of Suffolk England from the Humphrey de Bohun line of French royalty descended from Charlemagne, Jean Postell of Dieppe France, Alexander Pepin, Antoine Poitevin of Orsement France, and Jacques de Bordeaux of Grenoble, immigrated to the Charleston Orange district. They were very successful at marriage and property speculation. After petitioning the British Crown in 1697 for the right to own land in the Baronies, they prospered as slave owners on the Cooper, Ashepoo, Ashley and Santee River plantations they purchased from the British Landgrave Edmund Bellinger. Som

### MAP Evaluations

In [32]:
from haystack.components.evaluators import DocumentMAPEvaluator
MAP_evaluator = DocumentMAPEvaluator()
MAP_result = MAP_evaluator.run(
    ground_truth_documents=[[s] for s in selected_contexts],
    retrieved_documents=results
)

In [33]:
print(f"MAP Score: {MAP_result['score']}")

MAP Score: 0.7583333333333333


In [34]:
MAP_individual_scores = np.array(MAP_result["individual_scores"])

In [35]:
MAP_individual_scores

array([0.5       , 1.        , 0.5       , 0.25      , 1.        ,
       1.        , 0.33333333, 1.        , 1.        , 1.        ])

## Model-based Evaluation

### Context Relevance Evaluator

In [41]:
import os
from getpass import getpass

os.environ['OPENAI_API_KEY'] = getpass("Enter Generator API KEY")

In [42]:
from haystack.components.evaluators import ContextRelevanceEvaluator
CR_evaluator = ContextRelevanceEvaluator()
CR_result = CR_evaluator.run(questions=[[s] for s in selected_questions], contexts=[ [ r.content for r in  result] for result in results])

100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:19<00:00,  1.92s/it]


In [43]:
selected_questions[0]

'What was the name of the first Huguenot outpost in South Carolina?'

In [44]:
results[0]

[Document(id=353428544336c5f583b3615893a02833ae0292e04e3eaa3fa42cc726e84c8c0b, content: 'In the early years, many Huguenots also settled in the area of present-day Charleston, South Carolin...', score: 0.8162415027618408, embedding: vector of size 768),
 Document(id=ed0fe8d62c5c350afe712b9c0472232add089d2b6777c11512b92f8501f5e48d, content: 'French Huguenots made two attempts to establish a haven in North America. In 1562, naval officer Jea...', score: 0.8046768307685852, embedding: vector of size 768),
 Document(id=e3b57ff99911111f2f5ac5de998a0a7662ed031f6c4c482d085769edf4cc7f76, content: 'In 1700 several hundred French Huguenots migrated from England to the colony of Virginia, where the ...', score: 0.7907856702804565, embedding: vector of size 768),
 Document(id=b1f69ce4f07cb473347ac3af6132ebee77c70aed9e1cc3db0726421c4cbbf1f6, content: 'The first Huguenots to leave France sought freedom from persecution in Switzerland and the Netherlan...', score: 0.7895153760910034, embedding: vecto

In [45]:
CR_result['results'][0]

{'statements': ['In 1685, Rev. Elie Prioleau from the town of Pons in France, was among the first to settle in present-day Charleston, South Carolina.',
  'Huguenots made two attempts to establish a haven in North America with the first Huguenot outpost being Charlesfort on Parris Island, South Carolina.',
  'In 1564, René Goulaine de Laudonnière founded Fort Caroline in what is now Jacksonville, Florida as a Huguenot colony.',
  'The first Huguenots to leave France arrived in Brazil in 1555 to found France Antarctique.'],
 'statement_scores': [1, 1, 1, 0],
 'score': 0.75}

In [46]:
print(f"Context Relevance Score: {CR_result['score']}")

Context Relevance Score: 0.9166666666666666


In [47]:
CR_result['individual_scores']

[0.75, 1.0, 1.0, 1.0, 1.0, 0.6666666666666666, 1.0, 1.0, 1.0, 0.75]